project_id = "lnszidczioariaebsquo"

[functions.sla-monitor]
verify_jwt = false

[functions.trigger-automation]
verify_jwt = true

[functions.n8n-webhook]
verify_jwt = false

[functions.docs-signed-url]
verify_jwt = true

[functions.contact-docs-signed-url]
verify_jwt = true