// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idyylbutyreatrmidyqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkeXlsYnV0eXJlYXRybWlkeXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjQxMzksImV4cCI6MjA3MjkwMDEzOX0.KpE3fNMaAbYrwcNTcq1XOF2cbOgac6IouLcwq1xt_o8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});