// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxfmojbjjehyaisiikea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Zm1vamJqamVoeWFpc2lpa2VhIiwicm9zZSI6ImFub24iLCJpYXQiOjE3NTM5NDY2MjgsImV4cCI6MjA2OTUyMjYyOH0.vLAkBLPqa7viQ6kNPBvOZzcg42W_pmw_VXQCikZZoCM";

// Prefer environment variables when available (local dev), fall back to known-good values (Lovable)
const ENV = (import.meta as any)?.env ?? {};
const urlFromEnv = (ENV.VITE_SUPABASE_URL as string) || undefined;
const keyFromEnv = (ENV.VITE_SUPABASE_ANON_KEY as string) || undefined;
const url: string = urlFromEnv || SUPABASE_URL;
const key: string = keyFromEnv || SUPABASE_PUBLISHABLE_KEY;

// Debug logging per request
console.log('[SB] URL =', url);
console.log('[SB] KEY loaded =', !!key, 'len:', key?.length ?? 0);

if (!url || !key) {
  throw new Error('[SB] Supabase env vars missing. Check .env.development');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
